### ISSUE TITLE
Possible symbol visibility issues when compiling with LTO

### ISSUE THREAD

**Issue by hhoffstaette** [nondeterministic/mailfilter#6] opened 2022-08-24 06:45 UTC
Gentoo's Tinderbox (continuous build/QA system) found an issue in mailfilter:
https://bugs.gentoo.org/859514

This can be easily reproduced when configuring with LTO:
`./configure CFLAGS="$(echo $CFLAGS) -flto" CXXFLAGS="$(echo $CXXFLAGS) -flto"`

which gives:

```
g++ -Wall -pipe -march=native -O2 -flto   -o mailfilter md5c.o rcfile.o rcparser.o rfc822.o rfc822parser.o mailfilter.o header.o weeder.o preferences.o feedback.o filter.o score.o account.o protocol.o socket.o pop3.o apop.o imap.o   -lssl -lcrypto -lnsl 
rcparser.hh:140:7: warning: type 'union YYSTYPE' violates the C++ One Definition Rule [-Wodr]
  140 | union YYSTYPE
      |       ^
rfc822parser.hh:78:7: note: a different type is defined in another translation unit
   78 | union YYSTYPE
      |       ^
rcfile.yy:96:9: note: the first difference of corresponding definitions is field 'ival'
   96 |   int   ival;
      |         ^
rfc822.yy:68:8: note: a field with different name is defined in another translation unit
   68 | %union { char* sval; };
      |        ^
rc.tab.c:518:7: warning: type 'union yyalloc' violates the C++ One Definition Rule [-Wodr]
rfc.tab.c:433:7: note: a different type is defined in another translation unit
rc.tab.c:520:14: note: the first difference of corresponding definitions is field 'yyss_alloc'
rfc.tab.c:435:14: note: a field of same name but different type is defined in another translation unit
rc.tab.c:175:6: warning: type 'yysymbol_kind_t' violates the C++ One Definition Rule [-Wodr]
rfc.tab.c:148:6: note: an enum with different value name is defined in another translation unit
rc.tab.c:181:3: note: name 'YYSYMBOL_ALLOW' differs from name 'YYSYMBOL_HEADER_END' defined in another translation unit
rfc.tab.c:154:3: note: mismatching definition
```

This may or may not be a gcc-specific issue since building with clang/lld/LTO does not show any warning. To test/verify with clang:
```
./configure CC=clang CXX=clang++ CFLAGS="$(echo $CFLAGS) -flto=thin -fuse-ld=lld" CXXFLAGS="$(echo $CXXFLAGS) -flto=thin -fuse-ld=lld"
```

**Comment by hhoffstaette** [comment] 2022-08-28 19:02
So as expected this happens because the generated files contain un-namespaced symbols like YYSTYPE, union yyalloc, functions that should be static to the unit (yyalloc) etc. With a quick search & replace in rcparser.h/cc and rfc822parser.h/.cc (YYSTYPE -> rfc_YYSTYPE etc.) I could "fix" all these and got a clean build/link. Obviously the correct solution is to generate properly namespaced files.

**Comment by hhoffstaette** [comment] 2022-08-29 18:15
I found a rather complete and readable blog series [Generating C++ programs with flex and bison](https://learnmoderncpp.com/2020/12/16/generating-c-programs-with-flex-and-bison-1/). Maybe it helps - my flex/bison skills are long dead..

**Comment by nondeterministic** [comment] 2022-09-04 10:29
The problem is with having two parsers in one program, and it not being clear how to separate the two sufficiently. Some of it I could fix by using the appropriate prefix switches in flex and bison, but that did not rename all the affected symbols. So, I also had to add some rather ugly `#define`s in `rcfile.yy` and `rfc822.yy` as you can see in the current `master` branch.

Can you try, whether this fixes the issue on gentoo before I roll an official release? Needless to say, it fixes the problems here for me, when I add `-flto` (which I have done only temporary as I don't see a need to build with that switch enabled. It seems gentoo somehow pushed that flag in by itself, which is fine, but not essential to make mailfilter function properly).

Thanks in advance!

**Comment by hhoffstaette** [comment] 2022-09-04 10:53
Thank you for giving it a try. I think there is some kind of misunderstanding here.. the issue was not that mailfilter doesn't build/run in Gentoo or that Gentoo "somehow adds LTO". The QA server in question found this because it is trying to find packages that have problems with LTO, nothign more (since users can add compilation options for themselves any way they want). mailfilter works perfectly fine in Gentoo without LTO, which is the default and - as you said correctly - not really necessary or useful anyway.
However, the point was that there was indeed a symbol clash, so QA had a good point. ;)
Let me try master & report back.

**Comment by hhoffstaette** [comment] 2022-09-04 10:59
Tried master with gcc-12 and clang-14, both with LTO: no symbol clashes or warnings. :tada: 
Thank you!

**Comment by nondeterministic** [comment] 2022-09-04 11:02
No, thank you! Very helpful! I'm closing this issue.

**Closed as completed by nondeterministic** 2022-09-04 11:02 UTC

**Comment by hhoffstaette** [comment] 2022-09-04 11:04
> The problem is with having two parsers in one program, and it not being clear how to separate the two sufficiently. Some of it I could fix by using the appropriate prefix switches in flex and bison, but that did not rename all the affected symbols. So, I also had to add some rather ugly `#define`s in `rcfile.yy` and `rfc822.yy` as you can see in the current `master` branch.

That's why I suggested putting the parsers into separate C++ namespaces, with the `namespace` keyword - e.g. `mailfilter::rc` and `mailfilter::rfc`. But I guess just renaming the symbols does the trick as well.
